version: '3.7'

services:
  backend-ddd-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: backend-ddd-app
    container_name: backend-ddd-app
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
      - cache
    env_file: config/.env.docker
    environment:
      - NODE_ENV=docker
      - REDIS_HOST=cache
      - REDIS_PORT=6379
      - REDIS_PASSWORD=eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - app-network
    command: >
      sh -c "npm start"
  mongodb:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db
    networks:
      - app-network
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - cache:/data
volumes:
  cache:
    driver: local
  dbdata6:
    driver: local

networks:
    app-network:
      driver: bridge